# Window position on screen
position = "bottom-center"

# Margins (in pixels) from screen edges
margin_top = 10
margin_bottom = 10
margin_left = 10
margin_right = 10

# Animation (optional)
# Window transitions: slidedown, slideup, slideleft, slideright, swingdown, swingup, swingleft, swingright, fade, crossfade, none
window_transition = "slidedown"
window_transition_duration = 200

# Tab switching transitions: slidehorizontal, slidevertical, slidedown, slideup, slideleft, slideright, crossfade, none
stack_transition = "slidehorizontal"
stack_transition_duration = 200
