[default]
path = "/home/mephisto/Pictures/Wallpapers/"
duration = "30m"
sorting = "ascending"

[eDP-1]
path = "/home/mephisto/Pictures/Wallpapers/"
apply-shadow = true

[DP-2]
path = "/home/mephisto/Pictures/Wallpapers/"
sorting = "descending"
