[default]
path = "/home/mephisto/Pictures/Wallpapers/"
duration = "30m"
sorting = "random"

[eDP-1]
path = "/home/mephisto/Pictures/Wallpapers/"
duration = "30m"
sorting = "random"

[DP-2]
path = "/home/mephisto/Pictures/Wallpapers/"
duration = "30m"
sorting = "random"
