[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Dark"
opacity = 0.9
title = "Godlike"
