[font]
size = 12.0

[font.bold]
family = "HackNerdFont"
style = "Bold"

[font.bold_italic]
family = "HackNerdFont"
style = "Bold Italic"

[font.italic]
family = "HackNerdFont"
style = "Italic"

[font.normal]
family = "HackNerdFont"
style = "Regular"

[cursor]
blink_interval = 750

[cursor.style]
blinking = "On"

[env]
TERM = "xterm-256color"

[scrolling]
history = 20000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Dark"
opacity = 0.9
title = "Godlike"
